name = "ophemeral"
version = "0.1.0"

migrations_dir = "./priv/migrations"
schemafile = "./schema.sql"

[dependencies]
# webclient = { path = "../webclient" }
argus = { path = "../external/argus" }
feather = { path = "../external/feather" }
gleam_stdlib = ">= 0.38.0 and < 1.0.0"
wisp = ">= 0.14.0 and < 1.0.0"
mist = ">= 1.0.0 and < 2.0.0"
gleam_http = ">= 3.6.0 and < 4.0.0"
gleam_erlang = ">= 0.25.0 and < 1.0.0"
beecrypt = ">= 0.3.1 and < 1.0.0"
gwt = ">= 0.4.0 and < 1.0.0"
sqlight = ">= 0.9.0 and < 1.0.0"
gleam_json = ">= 1.0.1 and < 2.0.0"
birl = ">= 1.7.1 and < 2.0.0"
decode = ">= 0.2.0 and < 1.0.0"
lustre = ">= 4.3.0 and < 5.0.0"
shakespeare = ">= 0.1.2 and < 1.0.0"
formal = ">= 2.0.0 and < 3.0.0"
simplifile = ">= 2.0.1 and < 3.0.0"
dot_env = ">= 1.0.1 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
