name: 'Check Branch'

on:
  pull_request:
    branches:
      - main

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: github.base_ref == 'main' && github.head_ref != 'dev'
        run: |
          echo "::error title=forbiddenMerge::Merges to main only allowed from dev!"
          exit 1
