name: Fly Deploy Staging

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Deploy administration app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only -c fly.staging.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_ADMINISTRATION_STAGING_API_TOKEN }}
        working-directory: administration

