name: test

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  gleam-test:
    strategy:
      matrix:
        project: [backend]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ matrix.project }}
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.0.0"
          gleam-version: "1.2.1"
          rebar3-version: "3"
      - run: gleam deps download
      - run: gleam test
      - run: gleam format --check src test
